version: '3.4'

services:
  spi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spi
    entrypoint: [ "python", "./run.py", "--config-path", "/etc/config/worker_config.yaml", "--designated-task", "$DESIGNATED_TASK" ]
    environment:
      DESIGNATED_TASK: ''
    restart: on-failure
    volumes:
      - ${PWD}/examples/example_testing_config.yml:/etc/config/worker_config.yaml
      - ${PWD}/examples/example-activity.json:/etc/config/example-activity.json
    depends_on:
    - zookeeper
    - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock