streaming_platform:
    broker_url: "localhost:9092"
    auth:
        - user: null
        - pw: null


tasks:
    - name: "my first task"
      input_topic: "foo"
      input_offset_reset: latest
      topic_encoding: "utf8"
      storage_mode: "memory"
      output_topic: "bar"
      function:
          signature: "reduce_to_mean"
          args:
            keys: ['a']
          window:
            type: length
            value: 10
            grouping_keys: ['b']

      input_data_type: "json"

#    - name: "my second task"
#      input_topic: "foo"
#      topic_encoding: "utf8"
#      output_topic: "bar"
#      function:
#        signature: "drop_keys"
#        args:
#          keys: ['c']
#      input_data_type: "json"
