formatters:
  simple:
    format: ' %(message)s - %(levelname)s - %(asctime)s - %(name)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
loggers:
  default_logger: #do not change!
    handlers:
    - console
    level: DEBUG
    propagate: false

version: 1
