streaming_platform:
  type: kafka-testing
  broker_url: "kafka:9092"
  example_message_file: /etc/config/example-activity.json
  test_iterations: 10

task_defaults:
  input_offset_reset: earliest
  topic_encoding: utf8
  storage_mode: memory
  input_data_type: json


tasks:
- name: simple
  input_topic: foo
  output_topic: baa
  function:
    name: drop_keys
    args:
      keys: ['calories', 'athlete.id', 'laps[].calories', 'splits_metric[].average_heartrate']

- name: expensive
  input_topic: zoo
  output_topic: yaa
  function:
    name: reduce_to_mean
    args:
      keys: ['calories']
    window:
      type: length
      value: 100
      grouping_keys: ['id']